import "./globals.css";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";
import { fetchData } from "@/utils/fetchData";

export const metadata = {
  title: "Magnitude",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const [navDataLeft, navDataRight, mobileMenu, footerData] = await Promise.all(
    [
      fetchData(
        "https://chevaldemo.xyz/demo/magnitude/wp-json/custom/v1/menu/primary"
      ),
      fetchData(
        "https://chevaldemo.xyz/demo/magnitude/wp-json/custom/v1/menu/primaryright"
      ),
      fetchData(
        "https://chevaldemo.xyz/demo/magnitude/wp-json/custom/v1/menu/mobilemenu"
      ),
      fetchData(
        "https://chevaldemo.xyz/demo/magnitude/wp-json/custom/v1/footer_details"
      ),
    ]
  );
  return (
    <html
      lang="en"
      suppressHydrationWarning={true}
      className="notranslate"
      translate="no"
    >
      <body className={` antialiased flex flex-col min-h-screen`}>
        <Navbar
          navLeft={navDataLeft?.menu_tree}
          navRight={navDataRight?.menu_tree}
          mobileMenu={mobileMenu?.menu_tree}
        />
        <main className="flex-grow">
          {children}
          <ToastContainer />
        </main>
        <Footer data={footerData} />
      </body>
    </html>
  );
}
