import Navbar from "@/components/common/Navbar";
import "./globals.css";

export const metadata = {
  title: "Magnitude",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning={true}
      className="notranslate"
      translate="no"
    >
      <body className={` antialiased flex flex-col min-h-screen`}>
        <Navbar />
        <main className="flex-grow">{children}</main>
      </body>
    </html>
  );
}
