import Navbar from "@/components/common/Navbar";
import "./globals.css";
import Footer from "@/components/common/Footer";
import { fetchData } from "@/utils/fetchData";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
export const metadata = {
  title: "Magnitude",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const navDataLeft = await fetchData(
    "https://chevaldemo.xyz/demo/magnitude/wp-json/custom/v1/menu/primary"
  );
  const navDataRight = await fetchData(
    "https://chevaldemo.xyz/demo/magnitude/wp-json/custom/v1/menu/primaryright"
  );

  const mobileMenu = await fetchData(
    "https://chevaldemo.xyz/demo/magnitude/wp-json/custom/v1/menu/mobilemenu"
  );
  return (
    <html
      lang="en"
      suppressHydrationWarning={true}
      className="notranslate"
      translate="no"
    >
      <body className={` antialiased flex flex-col min-h-screen`}>
        <Navbar
          navLeft={navDataLeft?.menu_tree}
          navRight={navDataRight?.menu_tree}
          mobileMenu={mobileMenu?.menu_tree}
        />
        <main className="flex-grow">
          {children}
          <ToastContainer />
        </main>
        <Footer />
      </body>
    </html>
  );
}
